// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OctoView.Github.Contexts;
using System;

namespace OctoView.Github.Migrations
{
    [DbContext(typeof(GithubCacheContext))]
    [Migration("20180502204639_AddCachingModels")]
    partial class AddCachingModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BranchName");

                    b.Property<int?>("RepositoryId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("CachedBranches");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedPull", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee");

                    b.Property<int?>("BranchId");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<string>("Status");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("CachedPulls");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarUrl");

                    b.Property<int?>("PullId");

                    b.Property<string>("Status");

                    b.Property<string>("Url");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("PullId");

                    b.ToTable("CachedReviews");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.GithubRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique()
                        .HasFilter("[Owner] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.GithubRequest", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450);

                    b.Property<string>("Request");

                    b.HasKey("Key");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.UserRepository", b =>
                {
                    b.Property<int>("RepositoryId");

                    b.Property<string>("UserId");

                    b.HasKey("RepositoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRepository");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedBranch", b =>
                {
                    b.HasOne("OctoView.Github.Contexts.Models.GithubRepository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryId");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedPull", b =>
                {
                    b.HasOne("OctoView.Github.Contexts.Models.CachedBranch", "Branch")
                        .WithMany("Pulls")
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.CachedReview", b =>
                {
                    b.HasOne("OctoView.Github.Contexts.Models.CachedPull", "Pull")
                        .WithMany("Reviews")
                        .HasForeignKey("PullId");
                });

            modelBuilder.Entity("OctoView.Github.Contexts.Models.UserRepository", b =>
                {
                    b.HasOne("OctoView.Github.Contexts.Models.GithubRepository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OctoView.Github.Contexts.Models.User", "User")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
